name: Bug report
description: Create a report to help us improve
title: "[Bug] "
body:
  - type: checkboxes
    id: ensure
    attributes:
      label: Verify steps
      description: "
在提交之前，请确认
Please verify that you've followed these steps
"
      options:
        - label: "
如果你可以自己 debug 并解决的话，提交 PR 吧
Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
"
          required: true
        - label: "
我已经在 [Issue Tracker](https://github.com/j178/leetgo/issues) 和 [Discussion](https://github.com/j178/leetgo/discussions) 中找过我要提出的问题
I have searched on the [issue tracker](https://github.com/j178/leetgo/issues) and [Discussion](https://github.com/j178/leetgo/discussions) for a related issue.
"
          required: true
        - label: "
我已经使用 master 分支版本测试过，问题依旧存在
I have tested using the master branch, and the issue still exists.
"
          required: true
        - label: "
我已经仔细看过 [Documentation](https://github.com/j178/leetgo/blob/master/README.md) 并无法自行解决问题
I have read the [documentation](https://github.com/j178/leetgo/blob/master/README.md) and was unable to solve the issue.
"
          required: true
  - type: textarea
    attributes:
      label: "leetgo version"
      render: shell
      description: "
在下方附上 `leetgo -v` 的输出
Paste the output of `leetgo -v` below
"
    validations:
      required: true
  - type: textarea
    attributes:
      render: shell
      label: "leetgo config"
      description: "
在下方附上 `leetgo config` 的输出
Paste the output of `leetgo config` below
"
    validations:
      required: true
  - type: textarea
    attributes:
      render: shell
      label: Clash log
      description: "
请设置环境变量 `DEBUG=1`(PowerShell: `$env:DEBUG=1`, CMD: `set DEBUG=1`, Others: `export DEBUG=1`) 后再运行有问题的 leetgo 命令，并在下方附上 `leetgo` 的输出
Set environment variable `DEBUG=1`(PowerShell: `$env:DEBUG=1`, CMD: `set DEBUG=1`, Others: `export DEBUG=1`) and run the leetgo command that has the issue, and paste the output of `leetgo` below
"
  - type: textarea
    attributes:
      label: Description
    validations:
      required: true
